// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAccount = `-- name: AddAccount :one
INSERT INTO accounts (id, account_name, account_type, balance, created_at, updated_at, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, account_name, account_type, balance, created_at, updated_at, user_id
`

type AddAccountParams struct {
	ID          uuid.UUID
	AccountName string
	AccountType string
	Balance     float32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
}

func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addAccount,
		arg.ID,
		arg.AccountName,
		arg.AccountType,
		arg.Balance,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountType,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
