// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAccount = `-- name: AddAccount :one
INSERT INTO accounts (id, account_name, account_type, created_at, updated_at, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, account_name, account_type, created_at, updated_at, user_id
`

type AddAccountParams struct {
	ID          uuid.UUID
	AccountName string
	AccountType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
}

func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addAccount,
		arg.ID,
		arg.AccountName,
		arg.AccountType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts 
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, account_name, account_type, created_at, updated_at, user_id FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, account_name, account_type, created_at, updated_at, user_id FROM accounts
WHERE user_id = $1
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountInfo = `-- name: UpdateAccountInfo :one
UPDATE accounts
SET account_name = $2,
updated_at = NOW()
where id = $1
RETURNING id, account_name, account_type, created_at, updated_at, user_id
`

type UpdateAccountInfoParams struct {
	ID          uuid.UUID
	AccountName string
}

func (q *Queries) UpdateAccountInfo(ctx context.Context, arg UpdateAccountInfoParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountInfo, arg.ID, arg.AccountName)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.AccountName,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
