// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, category_name, created_at, updated_at, budget, user_id, group_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, category_name, created_at, updated_at, budget, user_id, group_id
`

type CreateCategoryParams struct {
	ID           uuid.UUID
	CategoryName string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Budget       string
	UserID       uuid.UUID
	GroupID      uuid.NullUUID
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ID,
		arg.CategoryName,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Budget,
		arg.UserID,
		arg.GroupID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Budget,
		&i.UserID,
		&i.GroupID,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategoriesByUser = `-- name: GetCategoriesByUser :many
SELECT id, category_name, created_at, updated_at, budget, user_id, group_id FROM categories
WHERE user_id = $1
`

func (q *Queries) GetCategoriesByUser(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Budget,
			&i.UserID,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, category_name, created_at, updated_at, budget, user_id, group_id FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Budget,
		&i.UserID,
		&i.GroupID,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET category_name = $2,
budget = $3,
group_id = $4,
updated_at = NOW()
WHERE id = $1
RETURNING id, category_name, created_at, updated_at, budget, user_id, group_id
`

type UpdateCategoryParams struct {
	ID           uuid.UUID
	CategoryName string
	Budget       string
	GroupID      uuid.NullUUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.CategoryName,
		arg.Budget,
		arg.GroupID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CategoryName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Budget,
		&i.UserID,
		&i.GroupID,
	)
	return i, err
}
