// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: joins.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT SUM(transactions.amount) AS account_balance
FROM accounts
INNER JOIN transactions
ON transactions.account_id = accounts.id
WHERE accounts.id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, id)
	var account_balance int64
	err := row.Scan(&account_balance)
	return account_balance, err
}

const getTransactionUserID = `-- name: GetTransactionUserID :one
SELECT accounts.user_id AS user_id FROM transactions
INNER JOIN accounts
ON accounts.id = transactions.account_id
WHERE transactions.id = $1
`

func (q *Queries) GetTransactionUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getTransactionUserID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserAccountsBalances = `-- name: GetUserAccountsBalances :many
SELECT accounts.id, accounts.account_name, accounts.account_type, accounts.created_at, accounts.updated_at, accounts.user_id, (SUM(transactions.amount * 100))::bigint AS account_balance_cents
FROM accounts
INNER JOIN transactions
ON transactions.account_id = accounts.id
WHERE accounts.user_id = $1
GROUP BY accounts.id
`

type GetUserAccountsBalancesRow struct {
	ID                  uuid.UUID
	AccountName         string
	AccountType         string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	UserID              uuid.UUID
	AccountBalanceCents int64
}

func (q *Queries) GetUserAccountsBalances(ctx context.Context, userID uuid.UUID) ([]GetUserAccountsBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAccountsBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAccountsBalancesRow
	for rows.Next() {
		var i GetUserAccountsBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.AccountBalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBudgetOverviewForMonth = `-- name: GetUserBudgetOverviewForMonth :many
SELECT categories.id AS category_id,
categories.category_name,
categories.budget,
categories.group_id,
groups.group_name,
COALESCE(SUM(-transactions.amount), 0)::numeric AS total_spent
FROM categories
LEFT JOIN groups ON groups.id = categories.group_id
LEFT JOIN transactions
ON transactions.category_id = categories.id
AND transactions.tx_date >= $2
AND transactions.tx_date < $3
WHERE categories.user_id = $1
GROUP BY categories.id, categories.category_name, categories.budget,
categories.group_id, groups.group_name
ORDER BY groups.group_name NULLS LAST, categories.category_name
`

type GetUserBudgetOverviewForMonthParams struct {
	UserID   uuid.UUID
	TxDate   time.Time
	TxDate_2 time.Time
}

type GetUserBudgetOverviewForMonthRow struct {
	CategoryID   uuid.UUID
	CategoryName string
	Budget       decimal.Decimal
	GroupID      uuid.NullUUID
	GroupName    sql.NullString
	TotalSpent   decimal.Decimal
}

func (q *Queries) GetUserBudgetOverviewForMonth(ctx context.Context, arg GetUserBudgetOverviewForMonthParams) ([]GetUserBudgetOverviewForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserBudgetOverviewForMonth, arg.UserID, arg.TxDate, arg.TxDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBudgetOverviewForMonthRow
	for rows.Next() {
		var i GetUserBudgetOverviewForMonthRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.Budget,
			&i.GroupID,
			&i.GroupName,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCategoriesDetailed = `-- name: GetUserCategoriesDetailed :many
SELECT categories.id, categories.category_name, categories.created_at, categories.updated_at, categories.budget, categories.user_id, categories.group_id,
groups.group_name
FROM categories
LEFT JOIN groups
ON groups.id = categories.group_id
WHERE categories.user_id = $1
`

type GetUserCategoriesDetailedRow struct {
	ID           uuid.UUID
	CategoryName string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Budget       decimal.Decimal
	UserID       uuid.UUID
	GroupID      uuid.NullUUID
	GroupName    sql.NullString
}

func (q *Queries) GetUserCategoriesDetailed(ctx context.Context, userID uuid.UUID) ([]GetUserCategoriesDetailedRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserCategoriesDetailed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCategoriesDetailedRow
	for rows.Next() {
		var i GetUserCategoriesDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Budget,
			&i.UserID,
			&i.GroupID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT transactions.id, transactions.amount, transactions.tx_description, transactions.tx_date, transactions.created_at, transactions.updated_at, transactions.posted, transactions.account_id, transactions.category_id,
accounts.account_name,
categories.category_name
FROM transactions
INNER JOIN accounts
ON accounts.id = transactions.account_id
INNER JOIN categories
ON categories.id = transactions.category_id
WHERE accounts.user_id = $1
ORDER BY transactions.tx_date DESC
`

type GetUserTransactionsRow struct {
	ID            uuid.UUID
	Amount        decimal.Decimal
	TxDescription string
	TxDate        time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Posted        bool
	AccountID     uuid.UUID
	CategoryID    uuid.NullUUID
	AccountName   string
	CategoryName  string
}

func (q *Queries) GetUserTransactions(ctx context.Context, userID uuid.UUID) ([]GetUserTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTransactionsRow
	for rows.Next() {
		var i GetUserTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TxDescription,
			&i.TxDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Posted,
			&i.AccountID,
			&i.CategoryID,
			&i.AccountName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
