// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: joins.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT SUM(transactions.amount) AS account_balance
FROM accounts
INNER JOIN transactions
ON transactions.account_id = accounts.id
WHERE accounts.id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, id)
	var account_balance int64
	err := row.Scan(&account_balance)
	return account_balance, err
}

const getTransactionUserID = `-- name: GetTransactionUserID :one
SELECT accounts.user_id AS user_id FROM transactions
INNER JOIN accounts
ON accounts.id = transactions.account_id
WHERE transactions.id = $1
`

func (q *Queries) GetTransactionUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getTransactionUserID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
