// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: joins.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT SUM(transactions.amount) AS account_balance
FROM accounts
INNER JOIN transactions
ON transactions.account_id = accounts.id
WHERE accounts.id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, id)
	var account_balance int64
	err := row.Scan(&account_balance)
	return account_balance, err
}

const getTransactionUserID = `-- name: GetTransactionUserID :one
SELECT accounts.user_id AS user_id FROM transactions
INNER JOIN accounts
ON accounts.id = transactions.account_id
WHERE transactions.id = $1
`

func (q *Queries) GetTransactionUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getTransactionUserID, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserAccountsBalances = `-- name: GetUserAccountsBalances :many
SELECT accounts.id, accounts.account_name, accounts.account_type, accounts.created_at, accounts.updated_at, accounts.user_id, (SUM(transactions.amount * 100))::bigint AS account_balance_cents
FROM accounts
INNER JOIN transactions
ON transactions.account_id = accounts.id
WHERE accounts.user_id = $1
GROUP BY accounts.id
`

type GetUserAccountsBalancesRow struct {
	ID                  uuid.UUID
	AccountName         string
	AccountType         string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	UserID              uuid.UUID
	AccountBalanceCents int64
}

func (q *Queries) GetUserAccountsBalances(ctx context.Context, userID uuid.UUID) ([]GetUserAccountsBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAccountsBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAccountsBalancesRow
	for rows.Next() {
		var i GetUserAccountsBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.AccountType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.AccountBalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT transactions.id, transactions.amount, transactions.tx_description, transactions.tx_date, transactions.created_at, transactions.updated_at, transactions.posted, transactions.account_id, transactions.category_id,
accounts.account_name,
categories.category_name
FROM transactions
INNER JOIN accounts
ON accounts.id = transactions.account_id
INNER JOIN categories
ON categories.id = transactions.category_id
WHERE accounts.user_id = $1
ORDER BY transactions.tx_date DESC
`

type GetUserTransactionsRow struct {
	ID            uuid.UUID
	Amount        decimal.Decimal
	TxDescription string
	TxDate        time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Posted        bool
	AccountID     uuid.UUID
	CategoryID    uuid.NullUUID
	AccountName   string
	CategoryName  string
}

func (q *Queries) GetUserTransactions(ctx context.Context, userID uuid.UUID) ([]GetUserTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTransactionsRow
	for rows.Next() {
		var i GetUserTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TxDescription,
			&i.TxDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Posted,
			&i.AccountID,
			&i.CategoryID,
			&i.AccountName,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
