// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID          uuid.UUID
	AccountName string
	AccountType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
}

type Category struct {
	ID           uuid.UUID
	CategoryName string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Budget       decimal.Decimal
	UserID       uuid.UUID
	GroupID      uuid.NullUUID
}

type Group struct {
	ID        uuid.UUID
	GroupName string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}

type Transaction struct {
	ID            uuid.UUID
	Amount        decimal.Decimal
	TxDescription string
	TxDate        time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Posted        bool
	AccountID     uuid.UUID
	CategoryID    uuid.NullUUID
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	HashedPw  string
}
