// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const addTransaction = `-- name: AddTransaction :one
INSERT INTO transactions (id, amount, tx_description, tx_date, created_at, updated_at, posted, account_id, category_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, amount, tx_description, tx_date, created_at, updated_at, posted, account_id, category_id
`

type AddTransactionParams struct {
	ID            uuid.UUID
	Amount        decimal.Decimal
	TxDescription string
	TxDate        time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Posted        bool
	AccountID     uuid.UUID
	CategoryID    uuid.NullUUID
}

func (q *Queries) AddTransaction(ctx context.Context, arg AddTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, addTransaction,
		arg.ID,
		arg.Amount,
		arg.TxDescription,
		arg.TxDate,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Posted,
		arg.AccountID,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.TxDescription,
		&i.TxDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Posted,
		&i.AccountID,
		&i.CategoryID,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, amount, tx_description, tx_date, created_at, updated_at, posted, account_id, category_id FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.TxDescription,
		&i.TxDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Posted,
		&i.AccountID,
		&i.CategoryID,
	)
	return i, err
}

const getTransactionsByAccount = `-- name: GetTransactionsByAccount :many
SELECT id, amount, tx_description, tx_date, created_at, updated_at, posted, account_id, category_id FROM transactions
WHERE account_id = $1
ORDER BY tx_date::date DESC, tx_date DESC
`

func (q *Queries) GetTransactionsByAccount(ctx context.Context, accountID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TxDescription,
			&i.TxDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Posted,
			&i.AccountID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByCategory = `-- name: GetTransactionsByCategory :many
SELECT id, amount, tx_description, tx_date, created_at, updated_at, posted, account_id, category_id FROM transactions
WHERE category_id = $1
`

func (q *Queries) GetTransactionsByCategory(ctx context.Context, categoryID uuid.NullUUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TxDescription,
			&i.TxDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Posted,
			&i.AccountID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET amount = $2,
tx_description = $3,
tx_date = $4,
updated_at = NOW(),
posted = $5,
account_id = $6,
category_id = $7
WHERE id = $1
RETURNING id, amount, tx_description, tx_date, created_at, updated_at, posted, account_id, category_id
`

type UpdateTransactionParams struct {
	ID            uuid.UUID
	Amount        decimal.Decimal
	TxDescription string
	TxDate        time.Time
	Posted        bool
	AccountID     uuid.UUID
	CategoryID    uuid.NullUUID
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.ID,
		arg.Amount,
		arg.TxDescription,
		arg.TxDate,
		arg.Posted,
		arg.AccountID,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.TxDescription,
		&i.TxDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Posted,
		&i.AccountID,
		&i.CategoryID,
	)
	return i, err
}
